### PR TITLE
Feature/add motion as control option

### PR DESCRIPTION
**Pull request by EMart002**
With this freature one can control the crazyflie with the Motion Control built in the iOS Devices.

### CODE REVIEW

**Comment by EMart002** [comment]
I was also thinking about integrating a flight gyroscopic instrument for a better explanation of the motion control feature. Maybe in the next commit.

**Comment by ataffanel** [comment]
Thanks! I am testing this evening.

**Comment by ataffanel** [comment]
Related to #5.

**Comment by ataffanel** [comment]
It does not compile because one file is missing:
```
Bridging header '/Users/arnaud/dev/crazyflie2-ios-client/Crazyflie client/Crazyflie clientTests-Bridging-Header.h' does not exist
```

This was added to the project in commit e7a7df49

**Comment by EMart002** [comment]
I have added this bridging header to the project and also accidently the xcodeproject file. Sorry for that. Please ignore that xcproj file. Thank you :)

**Comment by EMart002** [comment]
Hi @ataffanel did you already have the time to rereview the commits or is there anything from my side, i shall do? I'm already thinking about the idea of creating an Apple Watch app

**Comment by ataffanel** [comment]
Hi, No I havent had the time yet, sorry about that. Do you mean that I just have to remove the xcproj file and it should work? Is is possible for you to push a commit fixing this?

In any way I will test this evening and report my results.

**Comment by EMart002** [comment]
Hi, i just switched the DevelopmentTeam and the Bundle Identifier back to the origin, so you should be able to build this project without any problems. Hope it works :)

**Comment by ataffanel** [comment]
It is tested and merged, thanks!

We will have to change the mode 5 to something a bit more explicit though :-). It works quite well but it get some getting used to.

**Comment by EMart002** [comment]
:+1:  Cool! I'm glad, i was able to help :)

**Pull request merged**
