### PR TITLE
Updates for Swift 2.2 + Xcode 7.3

### PR DESCRIPTION
**Pull request by kouky**
Upgrade syntax and fix deprecation warnings.

### CODE REVIEW

**Comment by ataffanel** [comment]
Thanks for the PR! I will test later today and merge it. At a quick glance it seems that swift is getting cleaner for the ```#selector```, this looks better.

**Comment by kouky** [comment]
@ataffanel great! Just updated the PR to remove some unnecessary changes.

**Comment by ataffanel** [comment]
Tested and merged, thanks!

**Comment by kouky** [comment]
Thanks! :tada:

**Pull request merged**
